"""empty message

Revision ID: cb3d1e480de9
Revises: cd8258ac38e3
Create Date: 2022-08-26 18:18:13.443733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb3d1e480de9'
down_revision = 'cd8258ac38e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('character_age_key', 'character', type_='unique')
    op.drop_constraint('character_eye_color_key', 'character', type_='unique')
    op.drop_constraint('character_gender_key', 'character', type_='unique')
    op.drop_constraint('character_hair_color_key', 'character', type_='unique')
    op.drop_constraint('character_height_key', 'character', type_='unique')
    op.drop_constraint('planet_diameter_key', 'planet', type_='unique')
    op.drop_constraint('planet_orbital_period_key', 'planet', type_='unique')
    op.drop_constraint('planet_rotation_period_key', 'planet', type_='unique')
    op.drop_constraint('planet_terrain_key', 'planet', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('planet_terrain_key', 'planet', ['terrain'])
    op.create_unique_constraint('planet_rotation_period_key', 'planet', ['rotation_period'])
    op.create_unique_constraint('planet_orbital_period_key', 'planet', ['orbital_period'])
    op.create_unique_constraint('planet_diameter_key', 'planet', ['diameter'])
    op.create_unique_constraint('character_height_key', 'character', ['height'])
    op.create_unique_constraint('character_hair_color_key', 'character', ['hair_color'])
    op.create_unique_constraint('character_gender_key', 'character', ['gender'])
    op.create_unique_constraint('character_eye_color_key', 'character', ['eye_color'])
    op.create_unique_constraint('character_age_key', 'character', ['age'])
    # ### end Alembic commands ###
